### ISSUE TITLE
Cannot onboard AKS Cluster - issue with azure-arc-connectproxy-agent-deployment.yaml

### ISSUE THREAD

**Issue by jonathan-vella** [microsoft/azure_arc#429]
**Scenario which you are working on**
https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/aks/aks_arm_template/

**Describe the bug**
Onboarding fails at "az connectedk8s connect" command

**To Reproduce**
Update and execute onboarding script at https://raw.githubusercontent.com/microsoft/azure_arc/main/azure_arc_k8s_jumpstart/aks/arm_template/scripts/az_connect_aks.sh
Error: template: azure-arc-k8sagents/templates/azure-arc-connectproxy-agent-deployment.yaml:1:7: executing "azure-arc-k8sagents/templates/azure-arc-connectproxy-agent-deployment.yaml" at <index .Values.systemDefaultValues "connectproxy-agent" "enabled">: error calling index: indexof nil pointer

**Comment by lkamrat** [comment]
Can you please share AKS version you are using?

**Comment by likamrat** [comment]
@jonathan-vella I pushed a new onboarding script. do you mind try and report back?

**Comment by jonathan-vella** [comment]
Error persists. I'm using AKS version 1.19.7; 2 linux nodes + 2 x windows nodes both Standard_D2s_v3

**Comment by lkamrat** [comment]
I was to successfully deploy and connect with 1.18.4. can you try a non preview version of AKS?

**Comment by jonathan-vella** [comment]
Will do so and revert back. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by likamrat** [comment]
@jonathan-vella we found a critical typo so please use the new script in the PR

**Comment by jonathan-vella** [comment]
Sorted, thanks!
