### ISSUE TITLE
Doesn't create ArcBox-Client VM 

### ISSUE THREAD

**Issue by Zeeahm** [microsoft/azure_arc#683]
During deployment, the ARM template doesn't create ArcBox-Client VM. It doesn't matter which deployment method you use. For me, it creates only two VM ArcBox-CAPI-MGMT and ArcBox-K3s. I have tried this in different subscriptions but the result is the same.   

What I am missing here?

**Comment by likamrat** [comment]
Thank you @Zeeahm. Can you please share your params file and remove secrets?
Also, can you please share what you are seeing in the Deployment blade as well the log for the failure?
![image](https://user-images.githubusercontent.com/46730876/127359079-5a09708b-8bb5-4662-9f74-088067cf28ae.png)

**Comment by Zeeahm** [comment]
Here is the parameter file. 
![image](https://user-images.githubusercontent.com/61453518/127454763-a7f9ca17-29a2-478e-bac7-7ed0437daf3a.png)

**Deployment status**
![image](https://user-images.githubusercontent.com/61453518/127454991-8eae4a3c-5cdc-4565-810b-3083a25771f0.png)

In activity logs, it is failing during create or update VM extensions. 
![image](https://user-images.githubusercontent.com/61453518/127455226-f3f4f8d9-69b6-4b6a-9342-03868202aaeb.png)

**Comment by likamrat** [comment]
Associated with #688 . We are working on a fix

**Comment by likamrat** [comment]
Hi @Zeeahm can please try to re-deploy and report back? We pushed a fix to CAPI deployment here #688

**Comment by Zeeahm** [comment]
Hi, Still facing the same error. I used deployment option 1: Azure portal.

**Comment by dkirby-ms** [comment]
@Zeeahm can you please check your vCPU quota for the region you're deploying to?

**Comment by Zeeahm** [comment]
vCPU quota information
![image](https://user-images.githubusercontent.com/61453518/127977930-4efe4a04-8c4b-4704-becd-56c92e61e095.png)

Error Details
![image](https://user-images.githubusercontent.com/61453518/127977817-66f39afd-a976-4a97-b79f-3f9aea3089cf.png)

**Comment by likamrat** [comment]
@Zeeahm I would like to look at the _installCAPI.log_:
1. SSH to the _ArcBox-CAPI-MGMT_ VM
2. run the _sudo -s_ command
3. Paste the output of _cat /var/lib/waagent/custom-script/download/0/installCAPI.log_

**Comment by likamrat** [comment]
Closing this for now as we were not able to repro. @Zeeahm feel free to update on any change
